# H2 Setting Info (H2 Console? ???? ?? ???? ??)
# H2 Console? Path
# Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
spring:

  datasource:
    driver-class-name: org.h2.Driver  # Database? H2? ?????.
    url: jdbc:h2:tcp://localhost/~/datajpa
    # H2 ?? ??
    username: sa  # H2 ?? ? ??? username ?? (??? ??? ??)
    password:  #
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

